chatbot/urls.py
from django.urls import path
from chatbot import views

app_name = 'chatbot'

urlpatterns = [
    path("dashboard/", views.chatbot, name='chatbot_dashboard'),
    path("reply/", views.reply, name='reply')
]

gradia_vision/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('account/', include('accounts.urls')),
    path('student/', include('students.urls')),
    path('tutor/', include('tutors.urls')),
    path('chatbot/', include('chatbot.urls')),
]

students/urls.py
from django.urls import path
from students import views

urlpatterns = [
    path('signup/', views.signup_page, name="signup"),
    path('dashboard/', views.dashboard, name='student_dashboard'),
    path('upload/', views.upload, name='upload'),
    path('preview/', views.preview, name="preview"),
    path('preview/manage/', views.preview_manage, name="preview-manage"),
    path('notification/', views.notification_manage, name='notification'),
    path('graph/', views.graph_manage, name='graph'),
]

tutors/urls.py
from django.urls import path
from tutors import views

urlpatterns = [
    path('signup/', views.signup_page, name='signup'),
    path('dashboard/', views.dashboard, name='tutor_dashboard'),
    path('attendance/', views.upload, name='attendance'),
    path('risk/', views.risk, name='risk'),
    path('update/class/', views.update_class, name='update-class'),
    path('graph/', views.tutor_graph, name='tuor_graph'),
    path('notification/add/', views.add_notification, name="add_notification"),
]

students/models.py
from django.db import models
from accounts.models import UserProfile

import math

# Create your models here.

class Student(models.Model):
    profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    regno = models.CharField(max_length=20, unique=True)
    semester = models.IntegerField()
    department = models.CharField(max_length=200)
    course = models.CharField(max_length=200)
    current_class = models.CharField(max_length=10, blank=True)

    tutor_email = models.EmailField(max_length=255, default='teacher@gmail.com')

    toughness = models.JSONField(default=dict)
    study_hours = models.JSONField(default=dict)
    sleep_hours = models.JSONField(default=dict)

    def save(self, *args, **kwargs):
        self.current_class = self.course + str(math.ceil(self.semester/2))
        super().save(*args, **kwargs)

    def __str__(self):
        # user = self.profile.user
        return f"{self.regno} - Student"
    
class Subject(models.Model):
    course_code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=200)
    semester = models.IntegerField(default=0)
    credits = models.IntegerField()

    def __str__(self):
        return f"{self.course_code} - {self.semester} - Subject"
    
class SemesterResult(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    semester = models.IntegerField()
    sgpa = models.FloatField()
    total_credits = models.IntegerField()

    def __str__(self):
        return f"{self.semester} - {self.student.username}"
    
class StudentMark(models.Model):
    ASSESSMENT_CHOICES = [
        ('TH', 'Theory'),
        ('PR', 'Practical'),
    ]

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    # semester = models.IntegerField(default=1)
    semester = models.ForeignKey(SemesterResult, on_delete=models.CASCADE)

    assessment_type = models.CharField(
        max_length=2,
        choices=ASSESSMENT_CHOICES
    )

    cca_max = models.IntegerField()
    ese_max = models.IntegerField()
    cca_score = models.IntegerField()
    ese_score = models.IntegerField()
    total_max = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return f"{self.subject.course_code} - {self.semester} - {self.assessment_type} - {self.student.username}"

class Notification(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    message = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    tutor_name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.student.username} - {self.time}"
    

students/forms.py
from django import forms

class StudentForm(forms.Form):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Enter your name', 'id': 'username'}) )
    regno = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Enter your registration no', 'id': 'regno'}))
    semester = forms.IntegerField(min_value=1, max_value=8, widget=forms.TextInput(attrs={'placeholder': 'Enter your semester', 'id': 'semester'}))
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password' ,'id':'password'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':"Enter your email", 'id':'email'}))
    security_question = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': "Enter the question", 'id': 'security-question'}))
    security_answer = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Enter the answer', 'id': 'security-answer'}))

students/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

import json

from students.forms import StudentForm

from students.models import Student
from students.models import StudentMark
from students.models import Subject
from students.models import SemesterResult
from students.models import Notification
from accounts.models import UserProfile
from prediction.models import PredictionData
from prediction.models import Prediction
from tutors.models import AcademicRisk
from tutors.models import Tutor

from students.utils import extract_marklist_data_fyugp
from prediction.predict import predict_score

import math

# Create your views here.

def signup_page(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username'].strip()
            email = form.cleaned_data['email'].lower().strip()
            regno = form.cleaned_data['regno'].strip()
            semester = form.cleaned_data['semester']
            department = request.POST.get('department')
            course = request.POST.get('course')
            # password = request.POST.get('password')
            password = form.cleaned_data['password'].strip()
            confirm_password = request.POST.get('confirmPassword').strip()
            security_question =  form.cleaned_data['security_question']
            security_answer = form.cleaned_data['security_answer']

            # print(f"username: {username}")
            # print(f"email: {email}")
            # print(f"regno = {regno}")
            # print(f"semester = {semester}")
            # print(f"department = {department}")
            # print(f"course = {course}")
            # print(f"Password = {password}")
            # print(f"Confirmed Password = {confirm_password}")

            if Student.objects.filter(regno=regno).exists():
                form.add_error('regno', "Registration no already exist")
                print("Registration no already exist")
            else:
                if User.objects.filter(username=email).exists():
                    form.add_error('email', 'Email already exists')
                    print('student already exists')
                else:
                    if password != confirm_password:
                        form.add_error('password', "Both passwords should be same")
                        print("password error")
                    else:
                        user = User(username=email, email=email)
                        user.set_password(password)
                        user.save()

                        userProfile = UserProfile.objects.create(
                            user=user,
                            role='student',
                            security_question=security_question,
                        )
                        userProfile.security_answer = make_password(security_answer)
                        userProfile.save()

                        current_class = course + str(math.ceil(semester/2))

                        if Tutor.objects.filter(class_charge=current_class).exists():
                            tutor = Tutor.objects.filter(class_charge=current_class).order_by('-updated_at').first()
                            tutor_email = tutor.email
                        else:
                            tutor_email = "teacher@gmail.com"

                        student = Student.objects.create(
                            profile=userProfile,
                            username=username,
                            email=email,
                            regno=regno,
                            semester=semester,
                            department=department,
                            course=course,
                            tutor_email=tutor_email
                        )
                        student.save()

                        print("Successfull")
                        return redirect('/account/signin')
   
    else: 
        form = StudentForm()
    return render(request, 'students/signup.html', {
        'form': form,
    })


@login_required(login_url='signin')
def dashboard(request):
    user = request.user.userprofile.student
    current_class = user.course + str(math.ceil(user.semester/2))

    semester = SemesterResult.objects.filter(student=user).count()

    if request.method == "POST":
        # print(pdf_file)

        
            # print(extracted_data)


            ...
    else:
        return render(request, 'students/dashboard.html', {
            'name': user.username,
            'class': current_class,
            'semester': semester,
        })
        

    return render(request, 'students/dashboard.html', {
        'name': user.username,
        'class': current_class,
        'semester': semester,
    })

@login_required(login_url='signin')
def upload(request):
    extracted_data = None
    error = None
    user = request.user.userprofile.student

    if request.method == "POST":
        pdf_file = request.FILES.get("pdf")
        extracted_data = extract_marklist_data_fyugp(pdf_file)
        if extracted_data['name'] != user.username.upper():
            error = "Upload only your marklist"
            
            return render(request, 'students/upload.html', {
                'error': error,
            })
        
        if extracted_data['university'] != 'KANNUR UNIVERSITY':
            error = "Upload only your marklist"
            
            return render(request, 'students/upload.html', {
                'error': error,
            })

        course = extracted_data['programme']
        print(course)
        if 'Bachelor of Computer Application' in extracted_data['programme']:
            course = 'BCA'
        if course != user.course:
            error = "Upload only your marklist course"
            
            return render(request, 'students/upload.html', {
                'error': error,
            })

        if SemesterResult.objects.filter(student=user, semester=extracted_data['semester']).exists():
            error = f"Semester {extracted_data['semester']} marklist already uploaded."
            return render(request, 'students/upload.html', {
                'error': error,
            })
        else:
            semester_obj = SemesterResult.objects.create(
                student=user,
                semester=extracted_data['semester'],
                sgpa=extracted_data['sgpa'],
                total_credits=extracted_data['total']['credit']
            )
            for subject in extracted_data['subjects']:
                if not Subject.objects.filter(course_code=subject['code']).exists():
                    subject_obj = Subject.objects.create(
                        course_code=subject['code'],
                        name=subject['name'],
                        semester=extracted_data['semester'],
                        credits=subject['credit']
                    )
                else:
                    subject_obj = Subject.objects.get(course_code=subject['code'])
                StudentMark.objects.create(
                    student=user,
                    subject=subject_obj,
                    semester=semester_obj,
                    assessment_type='TH',
                    cca_max=subject['TH']['max']['cca'],
                    ese_max=subject['TH']['max']['ese'],
                    cca_score=subject['TH']['awarded']['cca'],
                    ese_score=subject['TH']['awarded']['ese'],
                    total_max=subject['TH']['max']['cca']+subject['TH']['max']['ese'],
                    total=subject['TH']['awarded']['cca']+subject['TH']['awarded']['ese'],
                )
                if 'PR' in subject:
                    StudentMark.objects.create(
                        student=user,
                        subject=subject_obj,
                        semester=semester_obj,
                        assessment_type='PR',
                        cca_max=subject['PR']['max']['cca'],
                        ese_max=subject['PR']['max']['ese'],
                        cca_score=subject['PR']['awarded']['cca'],
                        ese_score=subject['PR']['awarded']['ese'],
                        total_max=subject['PR']['max']['cca']+subject['PR']['max']['ese'],
                        total=subject['PR']['awarded']['cca']+subject['PR']['awarded']['ese'],
                    )

            semester_result = SemesterResult.objects.filter(student=user)
            all_sgpa = []
            for sem in semester_result:
                all_sgpa.append(sem.sgpa)

            if len(all_sgpa) !=1:
                student_mark_object = StudentMark.objects.filter(student=user)
                student_marks_percentage = []
                for i in student_mark_object:
                    student_marks_percentage.append((i.total/i.total_max)*100)
                # print(student_marks_percentage)
                average_mark = round(sum(student_marks_percentage)/len(student_marks_percentage), 2)
                # print(average_mark)

                average_sgpa = round(sum(all_sgpa)/len(all_sgpa), 2)
                previous_sgpa = all_sgpa[-1]
                sgpa_trend = round(all_sgpa[-2] - all_sgpa[-1], 2)

                predicted_score = predict_score(
                        previous_sgpa,
                        average_sgpa,
                        sgpa_trend,
                        average_mark,
                        3,
                        3,
                        5,
                        )

                if PredictionData.objects.filter(student=user).exists() and Prediction.objects.filter(student=user).exists():

students/templates/students/dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'students/css/dashboard.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <div class="sidebar-overlay" id="sidebar-overlay"></div>

    <div class="dashboard">
        <button value={{semester}} hidden id="current-sem">Sem</button>

        <!-- Sidebar -->
        <aside class="sidebar">
            <h2 class="logo">Gradia Vision</h2>

            <nav>
                <a href="#" class="nav-link active">🏠 Dashboard</a>
                <a href="{% url 'upload' %} " class="nav-link">📤 Upload Marklist</a>
                <a href="{% url 'preview' %} " class="nav-link">📄 Preview Results</a>
                <a href="{% url 'chatbot:chatbot_dashboard' %}" class="nav-link">🤖 Mentor Bot</a>
            </nav>

            <a href="{% url 'signout' %}" class="logout">🚪 Logout</a>
        </aside>

        <!-- Main Content -->
        <main class="main-content">

            <!-- Topbar -->
            <div class="topbar">
                <span class="menu-toggle" id="menu-toggle">☰</span>
                <div>
                    <h3>Welcome, {{ name }}</h3>
                    <p>Class: {{ class }}</p>
                </div>
            </div>

            <!-- Notifications -->
            <section class="card">
                <h3>🔔 Notifications</h3>

                <div class="notification-panel">
                    <table>
                        <thead>
                            <tr>
                                <th>Message</th>
                                <th>Sender</th>
                                <th>Date</th>
                                <th>Time</th>
                            </tr>
                        </thead>
                        <tbody id="table-body"></tbody>
                    </table>
                </div>
            </section>

            <!-- Graph Section -->
            <section class="card">
                <h3>📊 Performance Overview</h3>

                <div class="filters">
                    <select id="type">
                        <option value="course">Course</option>
                        <option value="sem">Semester</option>
                    </select>

                    <select id="semester">

                    </select>
                </div>

                <div class="graph-wrapper">
                    <canvas id="graph"></canvas>
                </div>
            </section>

        </main>
        <script src="{% static 'students/js/dashboard.js' %}"></script>
    </div>
    


</body>
</html>

students/templates/students/preview.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Preview page</title>
    <link rel="stylesheet" href="{% static 'students/css/preview.css' %}">
</head>
<body>
    <div class="page-header">
        <a href="{% url 'student_dashboard' %}" class="back-btn">← Back to Dashboard</a>
        <h1 class="page-title">📄 Preview Results</h1>
    </div>
    <select id="semester">
        {% for sem in current_sem %}
        <option value={{sem}}>Semester {{sem}}</option>
        {% endfor %}    
    </select>

    <div id="preview-area"></div>
    <table>
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Credit</th>
                <th>Type</th>
                <th>CCA</th>
                <th>CCA Total</th>
                <th>ESE</th>
                <th>ESE Total</th>
                <th>Total</th>
                <th>Total Max</th> 
                <th>Grade</th> 
            </tr>
        </thead>

        <tbody id="table-body"></tbody>
    </table>
    <div id="sgpa">
        <span>SGPA</span>
        <strong id="sgpa-value">8.5</strong>
    </div>

    <script src="{% static 'students/js/preview.js' %}"></script>
</body>
</html>

students/templates/students/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup - Student</title>
    <link rel="stylesheet" href="{% static 'students/css/signup.css' %}">
</head>
<body>

    <div class="container">
        <div class="container-image" id="container-image">
            <img src="{% static "accounts/img/three-characters.png" %}" alt="Characters">
        </div>

        <div class="container-element">

            <form method="post" id="signUpForm">
                {% csrf_token %}

                <h2 class="form-title">Create Student Account</h2>
        
                Name
                {{form.username}}
        
                Email
                {{form.email}}

                <div id="email-error" class="error"></div>

                {% if form.email.errors %}
                    <div class="error"> {{form.email.errors.0}} </div>
                {% endif %}
        
                Registration no
                {{form.regno}}

                {% if form.regno.errors %}
                    <div class="error"> {{form.regno.errors.0}} </div>
                {% endif %}
        
                Semester
                {{form.semester}} 

                <div id="semester-error" class="error"></div>
        
                Department
                <select name="department" id="department">
                    <option value="Commerce" >Department of Commerce</option>
                    <option value="Computer Science" selected>Department of Computer Science</option>
                    <option value="History">Department of History</option>
                </select>
        
                Course:
                <select name="course" id="course">
        
                </select>
        
                Password
                {{form.password}}

                Confirm Password
                <input type="password" name="confirmPassword" id="confirm-password" placeholder="Confirm password">

                {% if form.password.errors %}
                    <div class="error"> {{form.password.errors.0}} </div>
                {% endif %}
                <div id="password-error" class="error"></div>
        
                Question
                {{form.security_question}} 
                
                Answer
                {{form.security_answer}}
                
                <button id="submit-button" type="submit">Submit</button>
            </form>

        </div>
    </div>
    <script src="{% static "students/js/signup.js" %}"></script>
</body>
</html>

students/templates/students/student_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup - Student</title>
    <link rel="stylesheet" href="{% static 'students/css/signup.css' %}">
</head>
<body>
    <form method="post" id="signUpForm">
        {% csrf_token %}

        Name: {{form.username}} <br>

        Email: {{form.email}} <br>
        <div id="email-error" class="error"></div>
        {% if form.email.errors %}
            <div class="error"> {{form.email.errors.0}} </div>
        {% endif %}

        Registration no: {{form.regno}} <br>
        {% if form.regno.errors %}
            <div class="error"> {{form.regno.errors.0}} </div>
        {% endif %}

        Semester: {{form.semester}} <br>
        <div id="semester-error" class="error"></div>

        Department: 
        <select name="department" id="department">
            <option value="Commerce" >Department of Commerce</option>
            <option value="Computer Science" selected>Department of Computer Science</option>
            <option value="History">Department of History</option>
        </select> 
        <br>

        Course:
        <select name="course" id="course">

        </select>
        <br>

        <!-- Password: <input type="password" name="password" id="password"> <br> -->
        Password: {{form.password}} <br>
        Confirm Password: <input type="password" name="confirmPassword" id="confirm-password" placeholder="Confirm password"> <br>
        {% if form.password.errors %}
            <div class="error"> {{form.password.errors.0}} </div>
        {% endif %}
        <div id="password-error" class="error"></div>

        Question: {{form.security_question}} <br>
        Answer: {{form.security_answer}} <br>
        
        <button id="submit-button" type="submit">Submit</button>
    </form>
    <script src="{% static "students/js/signup.js" %}"></script>
</body>
</html>

students/templates/students/upload.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload</title>
    <link rel="stylesheet" href="{% static 'students/css/upload.css' %}">
</head>
<body>

    <div class="page-header">
        <a href="{% url 'student_dashboard' %}" class="back-btn">← Dashboard</a>
        <h1 class="page-title">📤 Upload Marklist</h1>
    </div>

    <div class="container">

        <form method="post" enctype="multipart/form-data" id="upload">
            {% csrf_token %}
    
            <input type="file" name="pdf" id="file" accept="application/pdf" required hidden> 

            <label for="file" class="file-upload">
                <img src="{% static 'img/upload.png' %}" alt="">
                <span class="upload-hint">Click to browse or drag & drop</span>
                <!-- <span class="upload-sub">PDF files only</span> -->
                <span id="filename"></span>
            </label>
    
            {% if success %}
                <div class="success-msg">{{ success }}</div>
            {% endif %}

            {% if error %}
                <div class="error">{{ error }}</div>
            {% endif %}
        
            {% if not success %}
                <button type="submit" id="upload-btn">Upload</button>
            {% endif %}
        </form>

    </div>
    
    <script src="{% static 'students/js/upload.js' %}"></script>
</body>
</html>